// ourobion nao — env generator (run by predev / prebuild; also `npm run gen-env`).
//
// You only ever edit two committed-as-*.example, gitignored-as-real files:
//   .env.public  → client-visible config (NEXT_PUBLIC_*). Next.js only exposes
//                  NEXT_PUBLIC_-prefixed vars to the browser bundle.
//   .env         → server-only secrets (R2 S3 creds for the local/CI D1 ETL, etc.).
//
// This script projects those into the two tool-specific files each runtime expects:
//   .env.public  ──▶  .env.local   (Next.js reads .env.local for NEXT_PUBLIC_* in dev/build)
//   .env         ──▶  .dev.vars    (wrangler/OpenNext local runtime secrets)
//
// Both OUTPUTS (.env.local, .dev.vars) are gitignored — never edit them by hand.
//
// Server code verifies Supabase access tokens against the project JWKS and so needs
// the Supabase project URL at runtime. The URL lives (publicly) in .env.public as
// NEXT_PUBLIC_SUPABASE_URL; we ALSO mirror it into .dev.vars as SUPABASE_URL so the
// server/edge layer has a non-NEXT_PUBLIC handle without duplicating the value by hand.
//
// Idempotent: rewrites the outputs from scratch each run. Missing inputs only warn
// (so a fresh clone without secrets can still `next dev` against public config).

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const appRoot = resolve(here, '..');
const p = (name) => resolve(appRoot, name);

const GENERATED_HEADER =
  '# GENERATED by scripts/gen-env.mjs — DO NOT EDIT. Edit .env / .env.public instead.\n';

/** Parse a dotenv file into ordered [key, value] pairs, preserving raw values. */
function parseDotenv(path) {
  if (!existsSync(path)) return null;
  const out = [];
  const text = readFileSync(path, 'utf8');
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (line === '' || line.startsWith('#')) continue;
    const eq = line.indexOf('=');
    if (eq === -1) continue;
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    if (key === '') continue;
    out.push([key, value]);
  }
  return out;
}

function serialize(pairs) {
  return GENERATED_HEADER + pairs.map(([k, v]) => `${k}=${v}`).join('\n') + '\n';
}

// .env.public ──▶ .env.local (client-visible config for Next.js)
const publicPairs = parseDotenv(p('.env.public'));
if (publicPairs === null) {
  console.warn('[gen-env] WARN: apps/nao/.env.public not found — skipping .env.local.');
  console.warn('[gen-env]       cp .env.public.example .env.public and fill it in.');
} else {
  writeFileSync(p('.env.local'), serialize(publicPairs));
  console.log(`[gen-env] wrote .env.local (${publicPairs.length} public vars).`);
}

// .env ──▶ .dev.vars (server-only secrets for the wrangler/OpenNext local runtime)
const secretPairs = parseDotenv(p('.env'));
if (secretPairs === null) {
  console.warn('[gen-env] WARN: apps/nao/.env not found — skipping .dev.vars.');
  console.warn('[gen-env]       cp .env.example .env and fill it in (R2 ETL creds, etc.).');
} else {
  const devVars = [...secretPairs];
  // Mirror the public Supabase URL into a server-only SUPABASE_URL handle (for JWKS).
  if (publicPairs !== null && !devVars.some(([k]) => k === 'SUPABASE_URL')) {
    const supaUrl = publicPairs.find(([k]) => k === 'NEXT_PUBLIC_SUPABASE_URL');
    if (supaUrl !== undefined) devVars.push(['SUPABASE_URL', supaUrl[1]]);
  }
  writeFileSync(p('.dev.vars'), serialize(devVars));
  console.log(`[gen-env] wrote .dev.vars (${devVars.length} server vars).`);
}
