// @ts-check
import { initOpenNextCloudflareForDev } from '@opennextjs/cloudflare';

/**
 * ourobion nao — Next.js config (App Router, deployed via @opennextjs/cloudflare
 * to Cloudflare Workers). Kept intentionally minimal; the OpenNext build is driven
 * by open-next.config.ts and wrangler.jsonc.
 *
 * initOpenNextCloudflareForDev() wires the Cloudflare bindings (CORPUS R2, DB D1)
 * into `next dev` so server code can call getCloudflareContext().env locally,
 * reading runtime secrets from .dev.vars (generated by scripts/gen-env.mjs).
 */
initOpenNextCloudflareForDev();

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // Pin the file-tracing root to THIS app. The repo has multiple lockfiles (root
  // supabase-CLI lockfile + this app's), so Next/OpenNext would otherwise infer the
  // monorepo root and over-bundle. Keeps the Worker bundle scoped to apps/nao.
  outputFileTracingRoot: import.meta.dirname,
};

export default nextConfig;
