-- M5b: insight_cards table with RLS
--
-- One row per (user_id, rule_id). The nightly generate-insights edge function
-- upserts cards whose rules are currently firing, refreshing generated_at and
-- extending expires_at by 7 days. Cards that stop firing expire naturally.
--
-- Users may update their own card status (snoozed / dismissed).
-- Dismissed cards are never regenerated by the engine.

-- ═══════════════════════════════════════════════════════════════
-- 1. INSIGHT_CARDS
-- ═══════════════════════════════════════════════════════════════

create table if not exists public.insight_cards (
  id                    bigint generated always as identity primary key,
  user_id               uuid not null references auth.users(id) on delete cascade,
  rule_id               text not null,

  generated_at          timestamptz not null default now(),
  title                 text not null,
  body                  text not null,

  category              text not null check (category in ('hydration', 'gut', 'vector', 'behaviour', 'descriptive')),
  severity              text not null check (severity in ('info', 'notice', 'watch')) default 'info',

  contributing_metrics  text[] not null default '{}',
  confidence_score      numeric(4,3) not null default 0 check (confidence_score between 0 and 1),
  confidence_sources    text[] not null default '{self_report}',

  status                text not null check (status in ('active', 'snoozed', 'dismissed')) default 'active',
  expires_at            timestamptz,
  phase_generated       text not null default 'phase1_stage1',

  unique (user_id, rule_id)
);

create index if not exists insight_cards_user_id_idx
  on public.insight_cards (user_id);

create index if not exists insight_cards_user_status_idx
  on public.insight_cards (user_id, status);

alter table public.insight_cards enable row level security;

create policy "Users can read own insight cards"
  on public.insight_cards for select
  using (auth.uid() = user_id);

-- Users may snooze or dismiss their own cards. The engine (service_role) handles inserts.
create policy "Users can update own insight card status"
  on public.insight_cards for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
